# suppress inspection "UnusedProperty"
logging:
  level:
    root: WARN
    com.zerotreedelta: INFO
    org:
      springframework:
        jdbc: INFO
        web: INFO

management:
  security:
    enabled: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/javascript,application/xml,text/html,text/xml,text/plain
  port: ${PORT}

    
spring:
  servlet:
     multipart:
        max-file-size: 30MB
        max-request-size: 30MB