# suppress inspection "UnusedProperty"
logging:
  level:
    root: WARN
    com.lfg.digital.digitools: INFO
    org:
      springframework:
        jdbc: INFO
        web: INFO

management:
  security:
    enabled: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/javascript,application/xml,text/html,text/xml,text/plain
  port: 8443
  ssl:
    enabled: true
    key-alias: server
    key-store-type: PKCS12
    key-store-provider: SUN
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-password: changeit